#ifndef _ONVIF_H_
#define _ONVIF_H_

#include "audio.h"
#include "debug.h"
#include <openssl/md5.h>

enum  ACTION_PTZ
{
	ACTION_PTZ_IDLE = 1,
	ACTION_PTZ_ALLIGN_AUTO_SPEED,
	ACTION_PTZ_ALLIGN_MAN_SPEED,
	ACTION_PTZ_STOP,
	ACTION_PTZ_LOCKED,
	ACTION_PTZ_MAX
};

typedef enum
{
	PTZ_TARGET_NOTHING = 0,
    PTZ_TARGET_ALL,
	PTZ_TARGET_STOP_PAN,
	PTZ_TARGET_STOP_TILT,
	PTZ_TARGET_STOP_FOCUS,
	PTZ_TARGET_STOP_ZOOM,
	PTZ_TARGET_CONT_MS_MOVE_PAN,
	PTZ_TARGET_CONT_MS_MOVE_TILT,
	PTZ_TARGET_CONT_MS_MOVE_FOCUS,
	PTZ_TARGET_CONT_MS_MOVE_ZOOM,
	PTZ_TARGET_STEP_MS_MOVE_PAN,
	PTZ_TARGET_STEP_MS_MOVE_TILT,
	PTZ_TARGET_STEP_MS_MOVE_FOCUS,
	PTZ_TARGET_STEP_MS_MOVE_ZOOM,
	PTZ_TARGET_ABSLT_MS_MOVE_PAN,
	PTZ_TARGET_ABSLT_MS_MOVE_TILT,
	PTZ_TARGET_ABSLT_MS_MOVE_FOCUS,
	PTZ_TARGET_ABSLT_MS_MOVE_ZOOM,
	PTZ_TARGET_CONT_AS_MOVE_PAN,
	PTZ_TARGET_CONT_AS_MOVE_TILT,
	PTZ_TARGET_CONT_AS_MOVE_FOCUS,
	PTZ_TARGET_CONT_AS_MOVE_ZOOM,
	PTZ_TARGET_STEP_AS_MOVE_PAN,
	PTZ_TARGET_STEP_AS_MOVE_TILT,
	PTZ_TARGET_STEP_AS_MOVE_FOCUS,
	PTZ_TARGET_STEP_AS_MOVE_ZOOM,
	PTZ_TARGET_ABSLT_AS_MOVE_PAN,
	PTZ_TARGET_ABSLT_AS_MOVE_TILT,
	PTZ_TARGET_ABSLT_AS_MOVE_FOCUS,
	PTZ_TARGET_ABSLT_AS_MOVE_ZOOM,
	PTZ_TARGET_STEP_RAW_PAN,
	PTZ_TARGET_STEP_RAW_TILT,
	PTZ_TARGET_STEP_RAW_FOCUS,
	PTZ_TARGET_STEP_RAW_ZOOM,
	PTZ_TARGET_ABSLT_RAW_PAN,
	PTZ_TARGET_ABSLT_RAW_TILT,
	PTZ_TARGET_ABSLT_RAW_FOCUS,
	PTZ_TARGET_ABSLT_RAW_ZOOM,
	PTZ_TARGET_SET_SPEED_PAN,
	PTZ_TARGET_SET_SPEED_TILT,
	PTZ_TARGET_SET_SPEED_FOCUS,
	PTZ_TARGET_SET_SPEED_ZOOM,
	PTZ_TARGET_SET_MODE_PAN,
	PTZ_TARGET_SET_MODE_TILT,
	PTZ_TARGET_SET_MODE_FOCUS,
	PTZ_TARGET_SET_MODE_ZOOM,
	PTZ_TARGET_CENTER_TARGET,
	PTZ_TARGET_RESET_OPTIC,
	PTZ_TARGET_TIME_MS_MOVE_PAN,
	PTZ_TARGET_TIME_MS_MOVE_TILT,
	PTZ_TARGET_TIME_MS_MOVE_FOCUS,
	PTZ_TARGET_TIME_MS_MOVE_ZOOM,
	PTZ_TARGET_TIME_AS_MOVE_PAN,
	PTZ_TARGET_TIME_AS_MOVE_TILT,
	PTZ_TARGET_TIME_AS_MOVE_FOCUS,
	PTZ_TARGET_TIME_AS_MOVE_ZOOM,
	PTZ_TARGET_ABSLT_RAW_FOCUS_FAST,
	PTZ_TARGET_STEP_RAW_FOCUS_FAST,
	PTZ_TARGET_UNLIM_RAW_STEP_MOVE_PAN = 64,
	PTZ_TARGET_UNLIM_RAW_STEP_MOVE_TILT,
	PTZ_TARGET_UNLIM_RAW_STEP_MOVE_FOCUS,
	PTZ_TARGET_UNLIM_RAW_STEP_MOVE_ZOOM,
	PTZ_TARGET_UNLIM_RAW_SPEED_PAN,
	PTZ_TARGET_UNLIM_RAW_SPEED_TILT,
	PTZ_TARGET_UNLIM_RAW_SPEED_FOCUS,
	PTZ_TARGET_UNLIM_RAW_SPEED_ZOOM,
	PTZ_TARGET_SAVE_MAX_MOVE_PAN = 96,
	PTZ_TARGET_SAVE_MIN_MOVE_PAN,
	PTZ_TARGET_SAVE_MAX_MOVE_TILT,
	PTZ_TARGET_SAVE_MIN_MOVE_TILT,
	PTZ_TARGET_SAVE_MAX_MOVE_FOCUS,
	PTZ_TARGET_SAVE_MIN_MOVE_FOCUS,
	PTZ_TARGET_SAVE_MAX_MOVE_ZOOM,
	PTZ_TARGET_SAVE_MIN_MOVE_ZOOM,
	PTZ_TARGET_SAVE_MAX_SPEED_PAN,
	PTZ_TARGET_SAVE_MIN_SPEED_PAN,
	PTZ_TARGET_SAVE_MAX_SPEED_TILT,
	PTZ_TARGET_SAVE_MIN_SPEED_TILT,
	PTZ_TARGET_SAVE_MAX_SPEED_FOCUS,
	PTZ_TARGET_SAVE_MIN_SPEED_FOCUS,
	PTZ_TARGET_SAVE_MAX_SPEED_ZOOM,
	PTZ_TARGET_SAVE_MIN_SPEED_ZOOM,
	PTZ_TARGET_SAVE_SENSOR_PAN,
	PTZ_TARGET_SAVE_SENSOR_TILT,
	PTZ_TARGET_SAVE_SENSOR_FOCUS,
	PTZ_TARGET_SAVE_SENSOR_ZOOM,
	PTZ_TARGET_SAVE_SETTINGS,
	PTZ_TARGET_RESET_SETTINGS,
	PTZ_TARGET_AUTO_CALIBRATE,
	PTZ_TARGET_LOCK = 128,
	PTZ_TARGET_UNLOCK,
	PTZ_TARGET_MAX
} PTZ_TARGET;

void onvif_start(unsigned int uiOnvifPt, unsigned int uiOnvifAuth, unsigned int uiRtspPt, MODULE_INFO* miCamera, MIC_LIST *nlMicList, unsigned int uiMicCnt, int uiPTZnum);
void onvif_stop();
int onvif_GetFocusPosition(int iZoomPos, int iMinFocusPos, int iMaxFocusPos);
void onvif_GotoHomePosition(unsigned int uiPtzID);
void onvif_GotoPresetPosition(unsigned int uiPtzID, unsigned int uiTarget);

#endif